version: "3.7"

services:
  cave:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - cave-net
    depends_on:
      - mysql
  mysql:
    container_name: cave-db
    platform: linux/x86_64
    image: mysql:8
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - cave-net
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
networks:
  cave-net: